services:
  caddy:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.caddy
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php
    depends_on:
      - mysql

  mysql:
    image: mysql:lts
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: korka
      MYSQL_USER: korka
      MYSQL_PASSWORD: korka
    ports:
      - 3306:3306
    volumes:
      - ./data/database:/var/lib/mysql

