services:
  caddy:
    image: caddy:2
    ports:
      - 80:80
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - ./src:/var/www/korka
      - ./assets:/var/www/korka/assets
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php
    volumes:
      - ./src:/var/www/korka
    depends_on:
      - mysql

  mysql:
    image: mysql:lts
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: korka
      MYSQL_USER: korka
      MYSQL_PASSWORD: korka
    ports:
      - 3306:3306
    volumes:
      - ./data/database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

