services:
  caddy:
    image: caddy:2
    ports:
      - 80:80
    volumes:
      - ./docker/Caddyfile.dev:/etc/caddy/Caddyfile
      - ./src:/var/www/korka
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php
    volumes:
      - ./src:/var/www/korka
    depends_on:
      - mysql

  mysql:
    image: mysql:lts
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: korka
      MYSQL_USER: korka
      MYSQL_PASSWORD: korka
    ports:
      - 3306:3306
    volumes:
      - ./data/database:/var/lib/mysql

